Build post item component
itoa-vn/docs pull request #12
Opened 2022-01-16 14:26 UTC by huynhtrunghieu2000

- [ ] Nguyên nhân, lý do
- [ ] Điều tra
- [ ] Hướng thay đổi 
- [ ] Phạm vi ảnh hưởng của thay đổi
- [ ] Kết quả
### Loại thay đổi
Sửa lỗi hoặc thêm/sửa tính năng

#### Nguyên nhân, lý do
Nguyên nhân gây lỗi hoặc lý do thực hiện thay đổi

#### Điều tra
Các thay đổi trong quá khứ gây ra lỗi hoặc điều tra các chức năng liên quan đến thay đổi

#### Hướng thay đổi

#### Phạm vi ảnh hưởng của thay đổi
Các hàm và chức năng bị thay đổi

#### Kết quả
Chụp ảnh màn hình, kết quả API

2022-01-17 00:26 UTC, truongduchuy910 commented
@huynhtrunghieu2000 Này bị thiếu các bước sau.
Issue chưa phân tích, chưa chuyển trạng thái sáng in progress
PR chưa link về Issue (bằng chức năng chứ không phải md), chưa link vào project, chưa đặt status.

2022-01-17 00:29 UTC, truongduchuy910 requested changes
### Một số vấn đề về quy trình

@huynhtrunghieu2000 Này bị thiếu các bước sau.
Issue chưa phân tích, chưa chuyển trạng thái sáng in progress
PR chưa link về Issue (bằng chức năng chứ không phải md), chưa link vào project, chưa đặt status.

Sao lại dời vào trong `./src` vậy mi. Cái ni trước khi làm việc mà không chắc cần phải báo vào đợi xác nhận tại issue trước khi mở nhánh để làm nha.

Để cấu trúc thư mục mặc định của nextJS và đặt components đồng cấp.
- node_modules
- components
- pages

> Quy trình: https://github.com/itoa-vn/docs/blob/main/docs/guide/task-life-cycle.md

2022-01-17 00:53 UTC, buihuongquynh commented on src/components/Post/Item/Detail.js
> +const Detail = ({ post }) => {
đoạn này ko có vấn đề gì nhưng nên code kiểu 
```
{
!post ? 
<>
        <span>Something wrong</span>
      </>
:
<div>
      <h3>{post.title}</h3>
      <img src={post.image} alt={post.title} />
      <div>
        <p>{post.content}</p>
      </div>
    </div>
 


}
```

2022-01-17 00:57 UTC, buihuongquynh commented on src/pages/index.js
> +
nên bọc 1 thẻ <div> hoặc <></> hoặc <Fragment> ngoài thẻ h1

2022-01-19 10:07 UTC, huynhtrunghieu2000 commented on src/components/Post/Item/Detail.js
> +const Detail = ({ post }) => {
chỗ này bọc ```if``` để dễ phân biệt thôi bạn, kiểu kia hơi khó nhìn á

2022-01-19 10:21 UTC, buihuongquynh approved these changes

2022-01-19 10:55 UTC, truongduchuy910 approved these changes

2022-01-19 10:56 UTC, vnd2k approved these changes

2022-01-19 11:01 UTC, merged