Api router
itoa-vn/docs pull request #15
Opened 2022-01-17 07:38 UTC by buihuongquynh

## Dành cho thay đổi, thêm mới tính năng
#### Thay đổi hoặc thêm mới gì
#### Mô tả hướng thay đổi, li do thay đổi.

## Dành cho sửa lỗi

#### Nguyên nhân
Nguyên nhân gây lỗi.

#### Điều tra
Các thay đổi trong quá khứ gây ra lỗi hoặc điều tra các chức năng liên quan đến thay đổi.
Các hiểu nhầm hoặc yêu cầu thay đổi gây ra lỗi.
Link pull request gây ra lỗi.

#### Hướng thay đổi
Hướng thực hiện thay đổi

## Phạm vi can thiệp
#### Màn hình (page)
#### Nhóm components
#### Schema (ItoaJS)

## Kết quả
Chụp ảnh màn hình, kết quả API

## Lưu ý

2022-01-18 16:09 UTC, truongduchuy910 approved these changes
Này em cần báo cáo rõ hơn để các thành viên vào sau đọc hiểu là em đang làm chi là được.

Ngang đây em đang khởi tạo GraphQL cho hén chạy theo hướng dẫn. Hướng dẫn có đính kèm trong trong issue. 

Và sẽ chỉnh sửa theo nhu cầu sử dụng ở pull request sau

2022-01-18 16:13 UTC, vnd2k approved these changes

2022-01-19 03:46 UTC, huynhtrunghieu2000 commented on pages/api/graphql.js
> +}
Thiếu endline

2022-01-19 03:47 UTC, huynhtrunghieu2000 requested changes

2022-01-19 03:47 UTC, huynhtrunghieu2000 commented on pages/api/resolvers/index.js
> +};
Thiếu endline

2022-01-19 03:47 UTC, huynhtrunghieu2000 commented on pages/api/schemas/index.js
> +    }`
Endline ở đây nữa

2022-01-19 08:47 UTC, closed without merging