Init base on example
itoa-vn/docs pull request #9
Opened 2022-01-16 03:29 UTC by buihuongquynh

- [ ] Nguyên nhân, lý do
- [ ] Điều tra
- [ ] Hướng thay đổi 
- [ ] Phạm vi ảnh hưởng của thay đổi
- [ ] Kết quả
### Loại thay đổi
Sửa lỗi hoặc thêm/sửa tính năng

#### Nguyên nhân, lý do
Nguyên nhân gây lỗi hoặc lý do thực hiện thay đổi

#### Điều tra
Các thay đổi trong quá khứ gây ra lỗi hoặc điều tra các chức năng liên quan đến thay đổi

#### Hướng thay đổi

#### Phạm vi ảnh hưởng của thay đổi
Các hàm và chức năng bị thay đổi

#### Kết quả
Chụp ảnh màn hình, kết quả API

2022-01-16 03:39 UTC, truongduchuy910 requested changes
Bỏ code trang này đi nha, để a khởi tạo apollo client để gọi graphQL.
Với lại gọi API bằng cái gì đó rồi chụp response của API làm kết quả

2022-01-16 03:41 UTC, buihuongquynh commented
ok

2022-01-16 03:47 UTC, truongduchuy910 commented
@buihuongquynh replace guide trong template thành - None nếu không có report chi để ghi nha.

2022-01-16 03:52 UTC, buihuongquynh commented
@truongduchuy910  replace guide  ở đâu a

2022-01-16 04:36 UTC, truongduchuy910 commented
@buihuongquynh 
- [x] Nguyên nhân, lý do
- [x] Điều tra
- [x] Hướng thay đổi 
- [x] Phạm vi ảnh hưởng của thay đổi
- [x] Kết quả
### Loại thay đổi
Thêm tính năng

#### Nguyên nhân, lý do
- None

#### Điều tra
- None


#### Hướng thay đổi

#### Phạm vi ảnh hưởng của thay đổi
- None

#### Kết quả
- None

2022-01-18 14:11 UTC, truongduchuy910 commented
@buihuongquynh gộp thành 1 commit rồi gỡ code gọi API đi như anh nói nha. PR này chỉ phát triển API thôi chứ không cần gọi và show.

Với lại sao để status là close vậy e?

2022-01-18 15:08 UTC, closed without merging